server:
  port: 80
  #servlet:
    #context-path: /Bazaar
spring:
  datasource:
    password: Mudit_1318
    url: jdbc:mysql://localhost:3306/bazaardb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  main:
    allow-circular-references: true  
   
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 761216355343-emg2a35p55lu3ee7svtdl5frrhn1u1tr.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 126923737133932
            client-secret: 131f99695dd21cb57ee74ca52eb39f58
            scope:
            - email
            - public_profile    
